// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Generate this file with credentials with the FlutterFire CLI

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDY_2XPUxtjat1xm1_4qRTEsQ5_-VxoBfs',
    appId: '1:401675165745:web:919652b7879011174c3510',
    messagingSenderId: '401675165745',
    projectId: 'playground-20240324',
    authDomain: 'playground-20240324.firebaseapp.com',
    storageBucket: 'playground-20240324.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJUT8SAiNQRSMwueJ81HNENssOWPBbHfw',
    appId: '1:401675165745:android:4fae5d64199ad76b4c3510',
    messagingSenderId: '401675165745',
    projectId: 'playground-20240324',
    storageBucket: 'playground-20240324.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwWXdLdo4_6ADJoy6wiGtLo9E81_e4-Jg',
    appId: '1:401675165745:ios:6c4e10b28db2cbc44c3510',
    messagingSenderId: '401675165745',
    projectId: 'playground-20240324',
    storageBucket: 'playground-20240324.appspot.com',
    iosBundleId: 'com.example.complete',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwWXdLdo4_6ADJoy6wiGtLo9E81_e4-Jg',
    appId: '1:401675165745:ios:bfa29b91c51e4c904c3510',
    messagingSenderId: '401675165745',
    projectId: 'playground-20240324',
    storageBucket: 'playground-20240324.appspot.com',
    iosBundleId: 'com.toshiakiezaki.playground',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDY_2XPUxtjat1xm1_4qRTEsQ5_-VxoBfs',
    appId: '1:401675165745:web:b0033a9a6591b8a94c3510',
    messagingSenderId: '401675165745',
    projectId: 'playground-20240324',
    authDomain: 'playground-20240324.firebaseapp.com',
    storageBucket: 'playground-20240324.appspot.com',
  );

}